/****** Object:  View [dbo].[View_JobHammerMillDestinationGroup]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [View_JobHammerMillDestinationGroup] AS SELECT  [BinIO]
										  ,[BinType]
										  ,[IngredientCode]
										  ,[Density]
										  ,[Volume]
										  ,[Weight]
										  ,[ActiveFilling]
										  ,[ActiveDischarge]
										  ,[BinUse]
										  ,[HighBin]
										  ,[BinPriority]
										  ,[FillingTime]
										  ,[LastTimeDischarge]
										  ,[LastFillingLot]
								   FROM [MasterSmartFeed].[dbo].BinIdentWeighing UNION SELECT [BinIO]
														  ,[BinType]
														  ,[IngredientCode]
														  ,[Density]
														  ,[Volume]
														  ,[Weight]
														  ,[ActiveFilling]
														  ,[ActiveDischarge]
														  ,[BinUse]
														  ,[HighBin]
														  ,[BinPriority]
														  ,[FillingTime]
														  ,[LastTimeDischarge]
														  ,[LastFillingLot]
											  FROM [MasterSmartFeed].[dbo].BinIdentPreWeighing
